local Tribe = "6"
--[[
  NOTE: YOU WILL HAVE TO CHANGE THE TRIBE NUMBER FOR SOME OF THEM ACCORDINGLY ^ (check dex and look at team colors to know which team you're on)
]]


local Players = game.Players
local LP = Players.LocalPlayer
local LPHead = LP.Character.Head

local TribeModel = "Tribe"..Tribe
if workspace:FindFirstChild("Team Tandem") then
    for i,v in pairs(workspace["Team Tandem"].Map[TribeModel].Flags:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            local partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
        end
    end
    wait()
    partToTouch = workspace["Team Tandem"].Map[TribeModel].Finish
    firetouchinterest(LPHead, partToTouch)
elseif workspace:FindFirstChild("Water and Fire") then
    for i,v in pairs(workspace["Water and Fire"].Map[TribeModel].Stations:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            firetouchinterest(LPHead, workspace["Water and Fire"].Map["Tribe"..Tribe].Trough.Water)
            wait(1)
            local partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
            wait(1)
            print("touching torch")
        end
    end
elseif workspace:FindFirstChild("Beat to the Punch") then
    for i,v in pairs(workspace["Beat to the Punch"].Map:GetChildren()) do
        if string.match(v.Name, "Tribe") then
            local partToTouch = v.Platforms:GetChildren()[2].Finish
            firetouchinterest(LPHead, partToTouch)
        end
    end
elseif workspace:FindFirstChild("Order Ordeal") then 
    --coconut: rbxassetid://5244795589
    --fire: rbxassetid://5244795956
    --fish: rbxassetid://5244795005
    --banana: rbxassetid://5244795956
    --tree: rbxassetid://5244794617
    --water: rbxassetid://5244793876
    workspace["Order Ordeal"].Map.Curtains:Destroy()
elseif workspace:FindFirstChild("Cargo Heist") then
    for i,v in pairs(workspace["Cargo Heist"].Map:GetChildren()) do
        v.Barrier:Destroy()
        --for a,b in pairs(v:GetChildren()) do

    end
    
elseif workspace:FindFirstChild("Holey Buckets") then
    local partToTouch = workspace["Holey Buckets"].Map.Water
    firetouchinterest(LPHead, partToTouch)
    for i,v in pairs(workspace["Holey Buckets"].Map[Tribe].Tube:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
        end
    end
    for i,v in pairs(workspace["Holey Buckets"].Map[Tribe].Key:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
        end
    end
    for i,v in pairs(workspace["Holey Buckets"].Map[Tribe].Finish:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
        end
    end
elseif workspace:FindFirstChild("Bag a Win") then
    for i,v in pairs(workspace["Bag a Win"].Map:GetDescendants()) do
        if v.Name == "Climbing Wall" or (v.Name == "Model" and string.match(v.Parent.Name, "Tribe")) then
            v:Destroy()
        end
    end
elseif workspace:FindFirstChild("Battering Brawl") then
    workspace["Battering Brawl"].Map.Out:Destroy() 
    --[[
            -- Script generated by SimpleSpy - credits to exx#9394

        local args = {
            [1] = game:GetService("Players").LocalPlayer.Character.Battering,
            [2] = game:GetService("Players").Israel7164.Character.Head,
            [3] = 1.3026183389805
        }

        game:GetService("ReplicatedStorage").Events.Game.Tool:FireServer(unpack(args))
    --]]
elseif workspace:FindFirstChild("Eye on the Prize") then --gather all items and put on wheel matching wheel on big board
    firetouchinterest(LPHead, workspace["Eye on the Prize"].Map["Tribe"..Tribe].Keys)
    firetouchinterest(LPHead, workspace["Eye on the Prize"].Map["Tribe"..Tribe].Finish)
elseif workspace:FindFirstChild("Buoy Baskets") then
--[[
--//COLLECT BUOY
local args = {
    [1] = workspace:FindFirstChild("Buoy Baskets").Piece.Handle,
    [2] = workspace:FindFirstChild("Buoy Baskets").Piece.Handle.Interact,
    [3] = true
}

game:GetService("ReplicatedStorage").Events.Game.Interact:FireServer(unpack(args))

--// SCORE EVERY TIME
local args = {
    [1] = game:GetService("Players").LocalPlayer.Character.Buoy,
    [2] = CFrame.new(Vector3.new(347.35430908203, 6.1014423370361, -265.51278686523), Vector3.new(0.48605895042419, 1.5186920165888e-08, 0.87392604351044)),
    [3] = 0.30674307686942
}

game:GetService("ReplicatedStorage").Events.Game.Tool:FireServer(unpack(args))

--]]
elseif workspace:FindFirstChild("Water Pressure") then
    for i,v in pairs(workspace["Water Pressure"].Map[TribeModel].Touch:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            local partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
            print(v:GetFullName(), "touched")
        end
    end
elseif workspace:FindFirstChild("Keys to Victory") then
    
elseif workspace:FindFirstChild("Shipwrecked") then
    for i,v in pairs(workspace["Shipwrecked"].Map[TribeModel]:GetDescendants()) do
        if v.Name == "Pile" then
            local partToTouch = v
            firetouchinterest(LPHead, partToTouch)
            print(v:GetFullName(), "touched")
        end
    end
    if workspace["Shipwrecked"].Map[TribeModel]:FindFirstChild("Boat1Complete") then
        local args = {
            [1] = "Shipwrecked",
            [2] = 5
        }

        game:GetService("ReplicatedStorage").Events.Competition.Client:FireServer(unpack(args))
    end
elseif workspace:FindFirstChild("Plane Patterns") then
    --[[ JUMP ON BRICK REMOTE
    local args = {
        [1] = 5,
        [2] = BrickColor.new(335)
    }

    game:GetService("ReplicatedStorage").Events.Competition.Custom:FireServer(unpack(args))
    --]]
elseif workspace:FindFirstChild("Flag it Down") then
    for i,v in pairs(workspace["Shipwrecked"].Map:GetDescendants()) do
        if v:IsA("TouchTransmitter") then
            local partToTouch = v.Parent
            firetouchinterest(LPHead, partToTouch)
            print(v:GetFullName(), "touched")
        end
    end
else
    warn("GAME NOT SUPPORTED")
end
